# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods_variation',
            old_name='name',
            new_name='variation_name',
        ),
    ]
