# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20180118_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='username',
        ),
    ]
